# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('source_port', models.PositiveIntegerField()),
                ('destination_host', models.CharField(max_length=255)),
                ('destination_port', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='portforward',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octopus.Service'),
        ),
    ]
